# Generated by Django 3.1.5 on 2021-03-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'car_brand',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand_id', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_model_brand', to='car_detail.carbrand')),
            ],
            options={
                'db_table': 'car_model',
            },
        ),
        migrations.CreateModel(
            name='CarVarient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand_id', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_var_brand', to='car_detail.carbrand')),
                ('model_id', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_var_model', to='car_detail.carmodel')),
            ],
            options={
                'db_table': 'car_varient',
            },
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_det_brand', to='car_detail.carbrand')),
                ('model_id', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_det_model', to='car_detail.carmodel')),
                ('varient_id', models.ForeignKey(db_column='varient_id', on_delete=django.db.models.deletion.CASCADE, related_name='car_det_var', to='car_detail.carvarient')),
            ],
            options={
                'db_table': 'car_detail',
            },
        ),
    ]
